### PR TITLE
Exclude folder parameter

### PR DESCRIPTION
**Pull request by peterkracik**
Added an option to exclude folders

### CODE REVIEW

**Review by easingthemes — APPROVED** [review]

**Comment by easingthemes** [comment]
Thanks

**Comment by Elanum** [comment]
Even with the setup of exclusion rules, my `docs` folder will get cleared when using ssh-deploy. 

if i run `rsync` locally, it wont delete the files:
```yml
- name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          ARGS: "-rltgoDzvO --delete"
          TARGET: ${{ secrets.SSH_DEV_DIR }}
          SOURCE: 'dist/'
          EXCLUDE: "/node_modules/, cgi-bin/*, .htaccess, docs/*, .well-known"
``` 

image

**Comment by peterkracik** [comment]
@Elanum what you mean by when you run it **locally** ? and by **delete** the file? it should not delete anything, it will just not synchronize these paths.

could you try it without whitespace after the comma?

**Comment by Elanum** [comment]
Locally i run:

```bash
rsync -rltgoDzvO --delete --exclude={'cgi-bin/*','.htaccess','docs/*','.well-known'} dist/ ****@***:***
```

and as you can see in my second screenshot Line 25, the action deletes the `text.txt` from the docs folder.

Also tried to use the EXCLUDE wihtout comma

**Comment by easingthemes** [comment]
This is not published yet.

**Comment by Elanum** [comment]
> This is not published yet.

Ahh okay, i see.
thank you :smiley:

**Comment by easingthemes** [comment]
Published in v2.1.6

**Pull request merged**
