### PR TITLE
Improved error handling. Added to README.md PM key generation details

### PR DESCRIPTION
**Pull request by GarryOne**
I was getting `Rsync error rsync exited with code 255` with no clue what's going wrong, even if I've used the exact example from the documentation. Downloaded and ran locally the node script and found out that it wasn't displaying the full error of rsync. Adding that I was able to do debugging.

So these are my changes:
* Improved error handling/logging.
* Changed of default `ARGS`  which wasn't built.
* Added to `README.md` the following note:
```
The keys should be generated using the PEM format. You can use this command
`ssh-keygen -m PEM -t rsa -b 4096`
```

### CODE REVIEW

**Comment by jerzabek** [comment]
Hey,
I am having a similar issue, but I was wondering why the keys should be generated in _PEM_ format?

**Comment by GarryOne** [comment]
@jerzabek yes, they should be. If you look at my PR, I edited `README.md`, adding:
```
The keys should be generated using the PEM format. You can us this command
`ssh-keygen -m PEM -t rsa -b 4096`
```

**Comment by easingthemes** [comment]
Thanks @GarryOne

**Comment by xqk1** [comment]
It's not working, so sad.

**Pull request merged**
