### PR TITLE
add optional `REMOTE_PORT` env to configuration

### PR DESCRIPTION
**Pull request by fmal**
@easingthemes thanks for creating this action! I need to provide custom ssh port, so i've added env for that. Hope you can merge 😃

### CODE REVIEW

**Comment by TrilipuT** [comment]
+1 
Same problem

**Comment by dennisedson** [comment]
+1

**Comment by easingthemes** [comment]
Thanks

**Comment by fdbatista** [comment]
@easingthemes I am having a problem with custom port. I tried to deploy via rsync command directly and it keeps returning a bad port exception, and using your Action only throws this error:

Screenshot from 2020-03-07 19-20-47

Which does not provide specific information about the error.
Exit error code 1 means bad usage, but how can I know exactly what is the problem?

Thanks.

**Pull request merged**
